(function() {

goog.provide('ogp_search_controller');

goog.require('gn_date_picker_directive');
goog.require('gn_date_validator_directive');

var module = angular.module('ogp_search_controller',
      ['ui.bootstrap.datetimepicker', 'gn_date_validator_directive',
      'ui.bootstrap', 'ui.select']);

/**
 * Controller for OpenGeoPortal search.
 */
module.controller('OgpSearchController', [
    '$scope', '$filter',
    function($scope, $filter) {
      $scope.step = 'searchForm';
      $scope.searching = false;
      $scope.searchForm = {};
      $scope.topicList = [
        { "id": "1", "label": "Topic 1"},
        { "id": "2", "label": "Topic 2"},
        { "id": "3", "label": "Topic 3"},
        { "id": "4", "label": "Topic 4"},
        { "id": "5", "label": "Topic 5"},
        { "id": "6", "label": "Topic 6"},
        { "id": "7", "label": "Topic 7"},
        { "id": "8", "label": "Topic 8"},
        { "id": "9", "label": "Topic 9"},
        { "id": "10", "label": "Topic 10"},
        { "id": "11", "label": "Topic 11"}
      ];

      $scope.dataTypeList = [
        { "id": "1", "label": "Data type 1"},
        { "id": "2", "label": "Data type 2"},
        { "id": "3", "label": "Data type 3"},
        { "id": "4", "label": "Data type 4"},
        { "id": "5", "label": "Data type 5"},
        { "id": "6", "label": "Data type 6"},
        { "id": "7", "label": "Data type 7"},
        { "id": "8", "label": "Data type 8"},
        { "id": "9", "label": "Data type 9"},
        { "id": "10", "label": "Data type 10"},
        { "id": "11", "label": "Data type 11"}
      ];
      $scope.dataRepositoryList = [
        { "id": "1", "label": "Data repository 1"},
        { "id": "2", "label": "Data repository 2"},
        { "id": "3", "label": "Data repository 3"},
        { "id": "4", "label": "Data repository 4"},
        { "id": "5", "label": "Data repository 5"},
        { "id": "6", "label": "Data repository 6"},
        { "id": "7", "label": "Data repository 7"},
        { "id": "8", "label": "Data repository 8"},
        { "id": "9", "label": "Data repository 9"},
        { "id": "10", "label": "Data repository 10"},
        { "id": "11", "label": "Data repository 11"}
        ];

      $scope.triggerSearch = function() {
        //Validate input form.
        $scope.searching = true;
        $scope.step = "searchResults";
        // Do search
        // Fill search results
        $scope.searchResults = [
          {"LayerId":"Tufts.BostonBuildings12","Name":"GISPORTAL.GISOWNER01.BOSTONBUILDINGS12","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Buildings Boston MA 2012","Publisher":"Boston (Mass.). Dept. of Innovation and Technology.","Originator":"Boston (Mass.). Dept. of Innovation and Technology.","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.399238,"MinY":42.228095,"MaxX":-70.923582,"MinX":-71.187645,"WorkspaceName":"sde","ContentDate":"2012-01-01T01:01:01Z","score":1.7334553},
          {"LayerId":"Tufts.BostonBuildings95","Name":"GISPORTAL.GISOWNER01.BOSTONBUILDINGS95","CollectionId":"initial collection","Institution":"Tufts","Access":"Restricted","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Buildings Boston MA 1995","Publisher":"Boston (Mass.) Water and Sewer Commission","Originator":"Boston (Mass.) Water and Sewer Commission","GeoReferenced":true,"Location":"{\"wms\": [\"https://geoserver02.uit.tufts.edu:8443/wms\"],\"wfs\": \"https://geoserver02.uit.tufts.edu:8443/wfs\"}","MaxY":42.396806,"MinY":42.227829,"MaxX":-70.953673,"MinX":-71.184869,"WorkspaceName":"sde","ContentDate":"1995-01-01T01:01:01Z","score":1.7334495},
          {"LayerId":"MIT.SDE_DATA.US_MA_BOSTON_G46BLDGS_2000","Name":"SDE_DATA.US_MA_BOSTON_G46BLDGS_2000","CollectionId":"geoserver","Institution":"MIT","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Boston, MA (Building Footprints, 2000)","Publisher":"Boston (MA) Boston Redevelopment Authority (BRA)","Originator":"Boston Water and Sewer Commission","GeoReferenced":true,"Location":"{\"wms\": [\"http://arrowsmith.mit.edu:8080/geoserver/wms\"],\"wfs\": \"http://arrowsmith.mit.edu:8080/geoserver/wfs\"}","MaxY":42.399411,"MinY":42.227829,"MaxX":-70.95365,"MinX":-71.186701,"WorkspaceName":"sde","ContentDate":"2000-01-01T01:01:01Z","score":1.7292681},
          {"LayerId":"Tufts.BostonStructures12","Name":"GISPORTAL.GISOWNER01.BOSTONSTRUCTURES12","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Structures Boston MA 2012","Publisher":"Boston (Mass.). Dept. of Innovation and Technology.","Originator":"Boston (Mass.). Dept. of Innovation and Technology.","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.399238,"MinY":42.228095,"MaxX":-70.923582,"MinX":-71.187645,"WorkspaceName":"sde","ContentDate":"2012-01-01T01:01:01Z","score":1.7230535},
          {"LayerId":"MIT.SDE_DATA.US_MA_BOSTONMET_G46BLDGHT_2002","Name":"SDE_DATA.US_MA_BOSTONMET_G46BLDGHT_2002","CollectionId":"geoserver","Institution":"MIT","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Boston Metro, MA (Building Footprints and Heights from LIDAR, 2002)","Publisher":"Massachusetts Office of Geographic and Environmental Information (MassGIS)","Originator":"3Di Technologies, Inc.(Now Spectrum Mapping LLC)","GeoReferenced":true,"Location":"{\"wfs\":\"http://arrowsmith.mit.edu:8080/geoserver/wfs\",\"wms\":[\"http://arrowsmith.mit.edu:8080/geoserver/wms\"]}","MaxY":42.4046,"MinY":42.223068,"MaxX":-70.953492,"MinX":-71.197465,"WorkspaceName":"sde","ContentDate":"2002-01-01T01:01:01Z","score":1.7209061},
          {"LayerId":"Tufts.CambridgePorches10","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEPORCHES10","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Porches Cambridge MA 2010","Publisher":"Cambridge (Mass.) Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.404108,"MinY":42.353502,"MaxX":-71.0653,"MinX":-71.16095,"WorkspaceName":"sde","ContentDate":"2010-01-01T01:01:01Z","score":1.6879362},
          {"LayerId":"Tufts.CambridgeDecks10","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEDECKS10","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Decks Cambridge MA 2010","Publisher":"Cambridge (Mass.) Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.404339,"MinY":42.352998,"MaxX":-71.069576,"MinX":-71.160875,"WorkspaceName":"sde","ContentDate":"2010-01-01T01:01:01Z","score":1.6879358},
          {"LayerId":"Tufts.CambridgeRooftopMechan03","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEROOFTOPMECHAN03","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Rooftop Mechanicals Cambridge MA 2003","Publisher":"Cambridge (Mass.) Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.402276,"MinY":42.353514,"MaxX":-71.07027,"MinX":-71.159277,"WorkspaceName":"sde","ContentDate":"2003-01-01T01:01:01Z","score":1.6782552},
          {"LayerId":"Tufts.BostonUnderConstr12","Name":"GISPORTAL.GISOWNER01.BOSTONUNDERCONSTR12","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Under Area Constructions Boston MA 2012","Publisher":"Boston (Mass.). Dept. of Innovation and Technology.","Originator":"Boston (Mass.). Dept. of Innovation and Technology.","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.395803,"MinY":42.251093,"MaxX":-71.005651,"MinX":-71.170169,"WorkspaceName":"sde","ContentDate":"2012-01-01T01:01:01Z","score":1.676333},
          {"LayerId":"HARVARD.SDE2.H006917193_V08_0005","Name":"SDE2.H006917193_V08_0005","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Sanborn map of Boston, Massachusetts, 1899 : Vol. 8 Dorchester, Index (Raster Image)","Publisher":"Harvard Map Collection, Harvard College Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.363766,"MinY":42.241634,"MinX":-71.197354,"MaxX":-70.999881,"ContentDate":"1899-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6740124},
          {"LayerId":"HARVARD.SDE2.H008768589_V05_0007","Name":"SDE2.H008768589_V05_0007","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Bromley map of Dorchester, Massachusetts, 1889 : Index Map (Raster Image)","Publisher":"Harvard Map Collection, Harvard Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.336988,"MinY":42.244821,"MinX":-71.119235,"MaxX":-71.012043,"ContentDate":"1889-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6740063},
          {"LayerId":"HARVARD.SDE2.CAMBRIDGE14PORCHES","Name":"SDE2.CAMBRIDGE14PORCHES","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Porches, Cambridge, Massachusetts, 2010 (pub. 2014)","Publisher":"City of Cambridge IT Department","Originator":"Cambridge (Mass.). Geographic Information Systems","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wfs\": \"http://hgl.harvard.edu:8080/geoserver/wfs\"}","MaxY":42.404108,"MinY":42.353502,"MinX":-71.16095,"MaxX":-71.0653,"ContentDate":"2010-01-01T01:01:01Z","WorkspaceName":"sde","GeoReferenced":true,"score":1.6685754},
          {"LayerId":"HARVARD.SDE2.CAMBRIDGE14DECKS","Name":"SDE2.CAMBRIDGE14DECKS","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Decks, Cambridge, Massachusetts, 2010 (pub. 2014)","Publisher":"City of Cambridge IT Department","Originator":"Cambridge (Mass.). Geographic Information Systems","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wfs\": \"http://hgl.harvard.edu:8080/geoserver/wfs\"}","MaxY":42.404339,"MinY":42.352998,"MinX":-71.160875,"MaxX":-71.069576,"ContentDate":"2010-01-01T01:01:01Z","WorkspaceName":"sde","GeoReferenced":true,"score":1.668575},
          {"LayerId":"HARVARD.SDE2.H006917193_001_0006","Name":"SDE2.H006917193_001_0006","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Sanborn map of Boston, Massachusetts, 1895 : Index (Raster Image)","Publisher":"Harvard Map Collection, Harvard College Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.40212,"MinY":42.336239,"MinX":-71.11679,"MaxX":-71.027083,"ContentDate":"1895-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6441861},
          {"LayerId":"HARVARD.SDE2.H006917193_V02_0005","Name":"SDE2.H006917193_V02_0005","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Sanborn map of Boston, Massachusetts, 1897 : Vol. 2 Back Bay : Index (Raster Image)","Publisher":"Harvard Map Collection, Harvard College Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.372317,"MinY":42.306474,"MinX":-71.139664,"MaxX":-71.040722,"ContentDate":"1897-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.64418},
          {"LayerId":"HARVARD.SDE2.H008768589_V05_0040","Name":"SDE2.H008768589_V05_0040","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Bromley map of Dorchester, Massachusetts, 1889 : Plate 33 (Raster Image)","Publisher":"Harvard Map Collection, Harvard Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.327313,"MinY":42.309048,"MinX":-71.05832,"MaxX":-71.027525,"ContentDate":"1889-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6441798},
          {"LayerId":"HARVARD.SDE2.H008768589_V05_0014","Name":"SDE2.H008768589_V05_0014","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Bromley map of Dorchester, Massachusetts, 1889 : Plate 7 (Raster Image)","Publisher":"Harvard Map Collection, Harvard Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.314188,"MinY":42.307029,"MinX":-71.055326,"MaxX":-71.040896,"ContentDate":"1889-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6441778},
          {"LayerId":"HARVARD.SDE2.H008768589_V05_0013","Name":"SDE2.H008768589_V05_0013","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Bromley map of Dorchester, Massachusetts, 1889 : Plate 6 (Raster Image)","Publisher":"Harvard Map Collection, Harvard Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.320181,"MinY":42.309946,"MinX":-71.064137,"MaxX":-71.048112,"ContentDate":"1889-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6441774},
          {"LayerId":"HARVARD.SDE2.H008768589_V05_0015","Name":"SDE2.H008768589_V05_0015","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Bromley map of Dorchester, Massachusetts, 1889 : Plate 8 (Raster Image)","Publisher":"Harvard Map Collection, Harvard Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.31657,"MinY":42.306328,"MinX":-71.066837,"MaxX":-71.051004,"ContentDate":"1889-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6441766},
          {"LayerId":"Tufts.ChelseaBuildingsPoly05","Name":"GISPORTAL.GISOWNER01.CHELSEABUILDINGSPOLY05","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Buildings Chelsea MA 2005","Publisher":"Chelsea (Mass.) Information Technology","Originator":"Chelsea (Mass.) Information Technology","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.415332,"MinY":42.384904,"MaxX":-71.010633,"MinX":-71.055014,"WorkspaceName":"sde","ContentDate":"2005-01-01T01:01:01Z","score":1.6439577},
          {"LayerId":"Tufts.ChelseaBuildingsLine05","Name":"GISPORTAL.GISOWNER01.CHELSEABUILDINGSLINE05","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Line","Availability":"Online","LayerDisplayName":"Buildings Chelsea MA 2005","Publisher":"Chelsea (Mass.). Information Technology Dept.","Originator":"Chelsea (Mass.). Information Technology Dept.","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.415332,"MinY":42.384904,"MaxX":-71.010633,"MinX":-71.055014,"WorkspaceName":"sde","ContentDate":"2005-01-01T01:01:01Z","score":1.6439577},
          {"LayerId":"Tufts.SomervilleBuildings99","Name":"GISPORTAL.GISOWNER01.SOMERVILLEBUILDINGS99","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Buildings Somerville MA 1999","Publisher":"Somerville (Mass.). Information Technology","Originator":"Somerville (Mass.) Information Technology","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.417523,"MinY":42.373223,"MaxX":-71.073016,"MinX":-71.134361,"WorkspaceName":"sde","ContentDate":"1999-01-01T01:01:01Z","score":1.6439509},
          {"LayerId":"Tufts.CambridgeBuildings95","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEBUILDINGS95","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Buildings Cambridge MA 1995","Publisher":"Cambridge (Mass.). Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.404471,"MinY":42.352989,"MaxX":-71.065012,"MinX":-71.161176,"WorkspaceName":"sde","ContentDate":"1995-01-01T01:01:01Z","score":1.6439489},
          {"LayerId":"Tufts.CambridgeBuildings10","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEBUILDINGS10","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Buildings Cambridge MA 2010","Publisher":"Cambridge (Mass.) Geographic Information Systems","Originator":"City of Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.404392,"MinY":42.351853,"MaxX":-71.065139,"MinX":-71.16131,"WorkspaceName":"sde","ContentDate":"2010-01-01T01:01:01Z","score":1.6439489},
          {"LayerId":"Tufts.CambridgeMuniBuilding06","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEMUNIBUILDING06","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Point","Availability":"online","LayerDisplayName":"Municipal Buildings Cambridge 2006","Publisher":"Cambridge (Mass.). Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.391918,"MinY":42.363494,"MaxX":-71.078306,"MinX":-71.155964,"WorkspaceName":"sde","ContentDate":"2006-01-01T01:01:01Z","score":1.6439465},
          {"LayerId":"Tufts.ArlingtonBuilding12","Name":"GISPORTAL.GISOWNER01.ARLINGTONBUILDING12","CollectionId":"geoserver","Institution":"Tufts","Access":"Restricted","DataType":"Polygon","Availability":"online","LayerDisplayName":"Buildings Arlington 2011","Publisher":"Arlington (Mass.). Information and Technology Dept.","Originator":"Arlington (Mass.). Information and Technology Dept.","GeoReferenced":true,"Location":"{\"wfs\":\"https://geoserver02.uit.tufts.edu:8443/wfs\",\"wms\":[\"https://geoserver02.uit.tufts.edu:8443/wms\"]}","MaxY":42.436362,"MinY":42.398599,"MaxX":-71.132602,"MinX":-71.202052,"WorkspaceName":"sde","ContentDate":"2011-01-01T01:01:01Z","score":1.6439453},
          {"LayerId":"Tufts.WatertownBldg10","Name":"GISPORTAL.GISOWNER01.WATERTOWNBLDG10","CollectionId":"geoserver","Institution":"Tufts","Access":"Restricted","DataType":"Polygon","Availability":"online","LayerDisplayName":"Buildings Watertown MA 2010","Publisher":"Watertown (Mass. : Town). Dept. of Community Development and Planning","Originator":"Watertown (Mass. : Town). Dept. of Community Development and Planning","GeoReferenced":true,"Location":"{\"wfs\":\"https://geoserver02.uit.tufts.edu:8443/wfs\",\"wms\":[\"https://geoserver02.uit.tufts.edu:8443/wms\"]}","MaxY":42.385971,"MinY":42.358483,"MaxX":-71.140587,"MinX":-71.216579,"WorkspaceName":"sde","ContentDate":"2010-01-01T01:01:01Z","score":1.6439375},
          {"LayerId":"Tufts.BrooklineBldg95","Name":"GISPORTAL.GISOWNER01.BROOKLINEBLDG95","CollectionId":"initial collection","Institution":"Tufts","Access":"Restricted","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Buildings Brookline MA 1995","Publisher":"Brookline (Mass.). Planning Dept.","Originator":"Brookline (Mass.). Planning Dept.","GeoReferenced":true,"Location":"{\"wms\": [\"https://geoserver02.uit.tufts.edu:8443/wms\"],\"wfs\": \"https://geoserver02.uit.tufts.edu:8443/wfs\"}","MaxY":42.351905,"MinY":42.294634,"MaxX":-71.106057,"MinX":-71.176351,"WorkspaceName":"sde","ContentDate":"1995-01-01T01:01:01Z","score":1.6439371},
          {"LayerId":"Tufts.WatertownBldgNum10","Name":"GISPORTAL.GISOWNER01.WATERTOWNBLDGNUM10","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Point","Availability":"online","LayerDisplayName":"Buildings Watertown MA 2010","Publisher":"Watertown (Mass.) Community Development and Planning","Originator":"Watertown (Mass.) Community Development and Planning","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.385793,"MinY":42.35888,"MaxX":-71.144434,"MinX":-71.215561,"WorkspaceName":"sde","ContentDate":"2010-01-01T01:01:01Z","score":1.6439371},
          {"LayerId":"Tufts.NewtonBldg07","Name":"GISPORTAL.GISOWNER01.NEWTONBLDG07","CollectionId":"geoserver","Institution":"Tufts","Access":"Restricted","DataType":"Polygon","Availability":"online","LayerDisplayName":"Buildings Newton MA 2007","Publisher":"Newton (Mass.). Engineering Department","Originator":"Newton (Mass.). Engineering Department","GeoReferenced":true,"Location":"{\"wfs\":\"https://geoserver02.uit.tufts.edu/wfs\",\"wms\":[\"https://geoserver02.uit.tufts.edu/wms\"]}","MaxY":42.366912,"MinY":42.287976,"MaxX":-71.157096,"MinX":-71.268016,"WorkspaceName":"sde","ContentDate":"2007-01-01T01:01:01Z","score":1.643931},
          {"LayerId":"MIT.SDE_DATA.US_MA_SOMERVILLE_G46BLDG_1999","Name":"SDE_DATA.US_MA_SOMERVILLE_G46BLDG_1999","CollectionId":"geoserver","Institution":"MIT","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Somerville, MA (Building Footprints, 1999)","Publisher":"Somerville (MA) Geographic Information System (City of Somerville GIS)","Originator":"Camp Dresser   McKee","GeoReferenced":true,"Location":"{\"wms\": [\"http://arrowsmith.mit.edu:8080/geoserver/wms\"],\"wfs\": \"http://arrowsmith.mit.edu:8080/geoserver/wfs\"}","MaxY":42.417517,"MinY":42.37324,"MaxX":-71.073039,"MinX":-71.134362,"WorkspaceName":"sde","ContentDate":"0001-01-01T01:01:01Z","score":1.639769},
          {"LayerId":"Tufts.MedfordBldgs9099","Name":"GISPORTAL.GISOWNER01.MEDFORDBLDGS9099","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Buildings Medford MA 1990-1999","Publisher":"Medford (Mass.). Engineering Division","Originator":"Medford (Mass.). Engineering Division","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.431331,"MinY":42.399895,"MaxX":-71.110245,"MinX":-71.144532,"WorkspaceName":"sde","ContentDate":"1990-01-01T01:01:01Z","score":1.6397675},
          {"LayerId":"Tufts.CambridgeBuildingAddresses07","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEBUILDINGADDRESSES07","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Point","Availability":"online","LayerDisplayName":"Building Addresses Cambridge MA 2007","Publisher":"Cambridge (Mass.). Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.4036,"MinY":42.35321,"MaxX":-71.070153,"MinX":-71.16017,"WorkspaceName":"sde","ContentDate":"2007-01-01T01:01:01Z","score":1.6397663},
          {"LayerId":"Tufts.ArlingtonSchool12","Name":"GISPORTAL.GISOWNER01.ARLINGTONSCHOOL12","CollectionId":"geoserver","Institution":"Tufts","Access":"Restricted","DataType":"Point","Availability":"online","LayerDisplayName":"Safety Buildings Arlington MA 2012","Publisher":"Arlington (Mass.). Information and Technology Dept.","Originator":"Arlington (Mass.). Information and Technology Dept.","GeoReferenced":true,"Location":"{\"wfs\":\"https://geoserver02.uit.tufts.edu:8443/wfs\",\"wms\":[\"https://geoserver02.uit.tufts.edu:8443/wms\"]}","MaxY":42.428946,"MinY":42.404111,"MaxX":-71.13807,"MinX":-71.18762,"WorkspaceName":"sde","ContentDate":"2012-01-01T01:01:01Z","score":1.639763},
          {"LayerId":"Tufts.ArlingtonSafetyBuild12","Name":"GISPORTAL.GISOWNER01.ARLINGTONSAFETYBUILD12","CollectionId":"geoserver","Institution":"Tufts","Access":"Restricted","DataType":"Point","Availability":"online","LayerDisplayName":"Safety Buildings Arlington MA 2012","Publisher":"Arlington (Mass.). Information and Technology Dept.","Originator":"Arlington (Mass.). Information and Technology Dept.","GeoReferenced":true,"Location":"{\"wfs\":\"https://geoserver02.uit.tufts.edu:8443/wfs\",\"wms\":[\"https://geoserver02.uit.tufts.edu:8443/wms\"]}","MaxY":42.419993,"MinY":42.41383,"MaxX":-71.149741,"MinX":-71.180811,"WorkspaceName":"sde","ContentDate":"2012-01-01T01:01:01Z","score":1.639762},
          {"LayerId":"MIT.SDE_DATA.US_MA_BROOKLINE_G46FTPRNT_2006","Name":"SDE_DATA.US_MA_BROOKLINE_G46FTPRNT_2006","CollectionId":"geoserver","Institution":"MIT","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Brookline, MA (Building Footprints, 2006)","Publisher":"Brookline (MA) Geographic Information System (City of Brookline GIS)","Originator":"Town of Brookline","GeoReferenced":true,"Location":"{\"wms\": [\"http://arrowsmith.mit.edu:8080/geoserver/wms\"],\"wfs\": \"http://arrowsmith.mit.edu:8080/geoserver/wfs\"}","MaxY":42.351915,"MinY":42.294634,"MaxX":-71.106041,"MinX":-71.176344,"WorkspaceName":"sde","ContentDate":"2006-01-01T01:01:01Z","score":1.6397551},
          {"LayerId":"HARVARD.SDE2.MATWN_3764_C2_2F7_1841_P3","Name":"SDE2.MATWN_3764_C2_2F7_1841_P3","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Fresh Pond, Cambridge, Massachusetts, 1841 (Raster Image)","Publisher":"Harvard Map Collection, Harvard College Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.393153,"MinY":42.377446,"MinX":-71.161568,"MaxX":-71.136952,"ContentDate":"1841-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.6356716},
          {"LayerId":"Tufts.ChelseaBuildingsWall05","Name":"GISPORTAL.GISOWNER01.CHELSEABUILDINGSWALL05","CollectionId":"initial collection","Institution":"Tufts","Access":"Public","DataType":"Line","Availability":"Online","LayerDisplayName":"Internal Building Walls Chelsea MA 2005","Publisher":"Chelsea (Mass.). Information Technology Dept.","Originator":"Chelsea (Mass.). Information Technology Dept.","GeoReferenced":true,"Location":"{\"wms\": [\"http://geoserver01.uit.tufts.edu/wms\"],\"wfs\": \"http://geoserver01.uit.tufts.edu/wfs\"}","MaxY":42.413626,"MinY":42.385858,"MaxX":-71.011063,"MinX":-71.050474,"WorkspaceName":"sde","ContentDate":"2005-01-01T01:01:01Z","score":1.6355933},
          {"LayerId":"Tufts.CambridgeBldgHighPts03","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEBLDGHIGHPTS03","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Point","Availability":"online","LayerDisplayName":"Building High Points Cambridge MA 2003","Publisher":"Cambridge (Mass.) Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.404356,"MinY":42.35308,"MaxX":-71.06511,"MinX":-71.16107,"WorkspaceName":"sde","ContentDate":"2003-01-01T01:01:01Z","score":1.635585},
          {"LayerId":"HARVARD.SDE2.CAMBRIDGE14BUILDINGS","Name":"SDE2.CAMBRIDGE14BUILDINGS","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Buildings, Cambridge, Massachusetts, 2010 (pub. 2014)","Publisher":"City of Cambridge IT Department","Originator":"Cambridge (Mass.). Geographic Information Systems","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wfs\": \"http://hgl.harvard.edu:8080/geoserver/wfs\"}","MaxY":42.404392,"MinY":42.351853,"MinX":-71.16131,"MaxX":-71.065139,"ContentDate":"2010-01-01T01:01:01Z","WorkspaceName":"sde","GeoReferenced":true,"score":1.635585},
          {"LayerId":"HARVARD.SDE2.CAMBRIDGE14MUNICIPALBUILDINGS","Name":"SDE2.CAMBRIDGE14MUNICIPALBUILDINGS","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Point","Availability":"Online","LayerDisplayName":"Miscellaneous Municipal Buildings, Cambridge, Massachusetts, 2014","Publisher":"Cambridge (Mass.). Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wfs\": \"http://hgl.harvard.edu:8080/geoserver/wfs\"}","MaxY":42.391918,"MinY":42.363494,"MinX":-71.155964,"MaxX":-71.078306,"ContentDate":"2014-01-01T01:01:01Z","WorkspaceName":"sde","GeoReferenced":true,"score":1.6355826},
          {"LayerId":"HARVARD.SDE2.MATWN_3764_C2_2H25_G46_1840_M3","Name":"SDE2.MATWN_3764_C2_2H25_G46_1840_M3","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Paper Map","Availability":"Online","LayerDisplayName":"Cambridge, Massachusetts, building lots, 1840 (Raster Image)","Publisher":"Harvard Map Collection, Harvard College Library","Originator":"Harvard Map Collection, Harvard College Library","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wcs\": \"http://hgl.harvard.edu:8080/geoserver/wcs\",\"download\": \"http://hgl.harvard.edu:8080/HGL/HGLOpenDelivery\"}","MaxY":42.377755,"MinY":42.3679,"MinX":-71.122439,"MaxX":-71.106054,"ContentDate":"1840-01-01T01:01:01Z","WorkspaceName":"cite","GeoReferenced":true,"score":1.635581},
          {"LayerId":"MIT.SDE_DATA.US_MA_NEWTON_C_G46BLDGS_1998","Name":"SDE_DATA.US_MA_NEWTON_C_G46BLDGS_1998","CollectionId":"geoserver","Institution":"MIT","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"Newton Center, MA (Building Footprint, 1998)","Publisher":"Newton (MA) Geographic Information System (City of Newton GIS)","Originator":"City of Newton GIS","GeoReferenced":true,"Location":"{\"wms\": [\"http://arrowsmith.mit.edu:8080/geoserver/wms\"],\"wfs\": \"http://arrowsmith.mit.edu:8080/geoserver/wfs\"}","MaxY":42.341735,"MinY":42.324549,"MaxX":-71.182553,"MinX":-71.202682,"WorkspaceName":"sde","ContentDate":"1998-01-01T01:01:01Z","score":1.6355653},
          {"LayerId":"MIT.SDE_DATA.US_MA_NEWTON_W_G46BLDGS_1998","Name":"SDE_DATA.US_MA_NEWTON_W_G46BLDGS_1998","CollectionId":"geoserver","Institution":"MIT","Access":"Public","DataType":"Polygon","Availability":"online","LayerDisplayName":"West Newton, MA (Building Footprints, 1998)","Publisher":"Newton (MA) Geographic Information System (City of Newton GIS)","Originator":"City of Newton GIS","GeoReferenced":true,"Location":"{\"wms\": [\"http://arrowsmith.mit.edu:8080/geoserver/wms\"],\"wfs\": \"http://arrowsmith.mit.edu:8080/geoserver/wfs\"}","MaxY":42.354443,"MinY":42.342624,"MaxX":-71.216457,"MinX":-71.240518,"WorkspaceName":"sde","ContentDate":"1998-01-01T01:01:01Z","score":1.6355625},
          {"LayerId":"HARVARD.SDE2.CAMBRIDGE14COMMERCIALPARKING","Name":"SDE2.CAMBRIDGE14COMMERCIALPARKING","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Point","Availability":"Online","LayerDisplayName":"Commercial Parking, Cambridge, Massachusetts, 2014","Publisher":"Cambridge (Mass.). Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wfs\": \"http://hgl.harvard.edu:8080/geoserver/wfs\"}","MaxY":42.395697,"MinY":42.354396,"MinX":-71.142203,"MaxX":-71.072265,"ContentDate":"2014-01-01T01:01:01Z","WorkspaceName":"sde","GeoReferenced":true,"score":1.6301639},
          {"LayerId":"HARVARD.SDE2.CAMBRIDGE14PARKINGLOTS","Name":"SDE2.CAMBRIDGE14PARKINGLOTS","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Polygon","Availability":"Online","LayerDisplayName":"Parking Lots, Cambridge, Massachusetts, 2010 (pub. 2014)","Publisher":"City of Cambridge IT Department","Originator":"Cambridge (Mass.). Geographic Information Systems","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wfs\": \"http://hgl.harvard.edu:8080/geoserver/wfs\"}","MaxY":42.403102,"MinY":42.352977,"MinX":-71.159325,"MaxX":-71.064038,"ContentDate":"2010-01-01T01:01:01Z","WorkspaceName":"sde","GeoReferenced":true,"score":1.6270763},
          {"LayerId":"HARVARD.SDE2.CAMBRIDGE14MUNIPARKINGLOTS","Name":"SDE2.CAMBRIDGE14MUNIPARKINGLOTS","CollectionId":"initial collection","Institution":"Harvard","Access":"Public","DataType":"Point","Availability":"Online","LayerDisplayName":"Municipal Parking Lots, Cambridge, Massachusetts, 2014","Publisher":"Cambridge (Mass.). Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","Location":"{\"wms\": [\"http://hgl.harvard.edu:8080/geoserver/wms\"],\"tilecache\": [\"http://hgl.harvard.edu/cgi-bin/tilecache/tilecache.cgi\"],\"serviceStart\": \"http://hgl.harvard.edu:8080/HGL/RemoteServiceStarter\",\"wfs\": \"http://hgl.harvard.edu:8080/geoserver/wfs\"}","MaxY":42.374294,"MinY":42.363992,"MinX":-71.122144,"MaxX":-71.078118,"ContentDate":"2014-01-01T01:01:01Z","WorkspaceName":"sde","GeoReferenced":true,"score":1.625001},
          {"LayerId":"Tufts.WatertownStruct10","Name":"GISPORTAL.GISOWNER01.WATERTOWNSTRUCT10","CollectionId":"geoserver","Institution":"Tufts","Access":"Restricted","DataType":"Point","Availability":"online","LayerDisplayName":"Structures Watertown MA 2010","Publisher":"Watertown (Mass.) Community Development and Planning","Originator":"Watertown (Mass. : Town). Dept. of Community Development and Planning","GeoReferenced":true,"Location":"{\"wfs\":\"https://geoserver02.uit.tufts.edu:8443/wfs\",\"wms\":[\"https://geoserver02.uit.tufts.edu:8443/wms\"]}","MaxY":42.386205,"MinY":42.358997,"MaxX":-71.144305,"MinX":-71.215571,"WorkspaceName":"sde","ContentDate":"2010-01-01T01:01:01Z","score":1.6166587},
          {"LayerId":"Tufts.WatertownLines10","Name":"GISPORTAL.GISOWNER01.WATERTOWNLINES10","CollectionId":"geoserver","Institution":"Tufts","Access":"Restricted","DataType":"Line","Availability":"online","LayerDisplayName":"Miscellaneous Lines Watertown MA 2010","Publisher":"Watertown (Mass. : Town). Dept. of Community Development and Planning","Originator":"Watertown (Mass. : Town). Dept. of Community Development and Planning","GeoReferenced":true,"Location":"{\"wfs\":\"https://geoserver02.uit.tufts.edu:8443/wfs\",\"wms\":[\"https://geoserver02.uit.tufts.edu:8443/wms\"]}","MaxY":42.384934,"MinY":42.358975,"MaxX":-71.153819,"MinX":-71.211655,"WorkspaceName":"sde","ContentDate":"2010-01-01T01:01:01Z","score":1.6166579},
          {"LayerId":"Tufts.CambridgePostOffices05","Name":"GISPORTAL.GISOWNER01.CAMBRIDGEPOSTOFFICES05","CollectionId":"geoserver","Institution":"Tufts","Access":"Public","DataType":"Point","Availability":"online","LayerDisplayName":"Post Offices Cambridge MA 2005","Publisher":"Cambridge (Mass.). Geographic Information Systems","Originator":"Cambridge (Mass.). Geographic Information Systems","GeoReferenced":true,"Location":"{\"wfs\":\"http://geoserver01.uit.tufts.edu/wfs\",\"wms\":[\"http://geoserver01.uit.tufts.edu/wms\"]}","MaxY":42.390002,"MinY":42.35893,"MaxX":-71.080821,"MinX":-71.122906,"WorkspaceName":"sde","ContentDate":"2005-01-01T01:01:01Z","score":1.6151248}
        ];
        $scope.searching = false;

      };

      $scope.reviseSearch = function() {
        $scope.searchResults = [];
        $scope.searching = false;
        $scope.step ="searchForm";
      };

      $scope.newSearch = function() {
        $scope.searchResults = [];
        $scope.searching = false;
        $scope.searchForm = {};
        $scope.step ="searchForm";
      };


    }]);








})();